services:
  vehicle-tracking-app:
    build: .
    ports:
      - "7000:7000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-container:5432/vehicle_tracking_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-postgres}
    depends_on:
      postgres-db-container:
        condition: service_healthy

  postgres-db-container:
    image: postgres:15
    environment:
      POSTGRES_DB: vehicle_tracking_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache-container:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: